name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: build and push
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: beep42/siteseek:latest
